run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - stylecheck
    - gosimple
    - govet
    - ineffassign
    - copyloopvar
    - staticcheck
    - typecheck
    - unconvert

output:
  formats:
    - format: colored-line-number

  print-issued-lines: true

  print-linter-name: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
