version: "3.9"
name: AvitoTest_GolovlevFedor
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "JustAUser"
      POSTGRES_PASSWORD: "JustAPassword"
    ports:
      - "5432:5432"
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_ADDRESS=postgres:5432
    ports:
      - "8080:8080"